name: Cleanup
on:
  workflow_dispatch

jobs:

  # Demonstrate how to delete by name
  delete-by-name:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Delete Artifact by Name
        uses: jimschubert/delete-artifacts-action@v1
        with:
          log_level: 'debug'
          artifact_name: '${{ github.event.client_payload.base_name }}'
          min_bytes: '0'
